name: Docker

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image & push
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest

          docker build -t ghcr.io/bitprocessor/drone-docker-buildx-ecr:$VERSION . 
          docker push ghcr.io/bitprocessor/drone-docker-buildx-ecr:$VERSION
          if [ "$VERSION" != "latest" ] ; then
            docker tag ghcr.io/bitprocessor/drone-docker-buildx-ecr:$VERSION ghcr.io/bitprocessor/drone-docker-buildx-ecr:latest
            docker push ghcr.io/bitprocessor/drone-docker-buildx-ecr:latest
          fi
